=== CuentaEducaSantiago/2324_Imsgi_SantiagoGV/ud4/10/10.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- Declaracion de tipos -->
    <xs:simpleType name="tipotiempo">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="999"/>
        </xs:restriction>
        </xs:simpleType>
        <!-- Principal -->
        <xs:element name="pagina">
        <xs:complexType>
        <xs:sequence>
        <xs:element name="receta" maxOccurs="unbounded">
        <xs:complexType>
        <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="descripcion" type="xs:string" minOccurs="0"/>
        <xs:element name="tiempo">
        <xs:complexType>
        <xs:attribute name="coccion" type="tipotiempo"/>
        <xs:attribute name="preparacion" use="optional" type="tipotiempo"/>
        </xs:complexType>
        </xs:element>
        <xs:element name="ingredientes">
        <xs:complexType>
        <xs:sequence>
        <xs:element name="ingrediente" maxOccurs="unbounded">
        <xs:complexType mixed="true">
        <xs:sequence>
        <xs:element name="cantidad" minOccurs="0">
        <xs:complexType>
        <xs:simpleContent>
        <xs:extension base="xs:positiveInteger">
        <xs:attribute name="unidad" default="gramo" use="optional">
        <xs:simpleType>
        <xs:restriction base="xs:string">
        <xs:pattern value="gramo|pizca|mililitro|cucharada|chorro"/>
        </xs:restriction>
        </xs:simpleType>
        </xs:attribute>
        </xs:extension>
        </xs:simpleContent>
        </xs:complexType>
        </xs:element>
        </xs:sequence>
        </xs:complexType>
        </xs:element>
        </xs:sequence>
        </xs:complexType>
        </xs:element>
        <xs:element name="instrucciones" minOccurs="0">
        <xs:complexType>
        <xs:sequence>
        <xs:element name="paso" maxOccurs="10"/>
        </xs:sequence>
        </xs:complexType>
        </xs:element>
        </xs:sequence>
        <xs:attribute name="plato" default="Primero">
        <xs:simpleType>
        <xs:restriction base="xs:string">
        <xs:pattern value="Primero|Segundo|Postre"/>
        </xs:restriction>
        </xs:simpleType>
        </xs:attribute>
        </xs:complexType>
        </xs:element>
        </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== CuentaEducaSantiago/2324_Imsgi_SantiagoGV/ud4/10/10.xml
<pagina xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="10.xsd">
    <receta plato="Primero">
        <nombre>Risotto milanesa</nombre>
        <tiempo coccion="20"/>
            <ingredientes>
                <ingrediente>Arroz
                <cantidad unidad="gramo">500</cantidad>
                </ingrediente>
                <ingrediente>
                Cebolla mediana
                <cantidad>1</cantidad>
                </ingrediente>
                <ingrediente>
                Azafrá
                <cantidad unidad="pizca">1</cantidad>
                </ingrediente>
                <ingrediente>
                Queso parmesano
                <cantidad unidad="gramo">100</cantidad>
                </ingrediente>
                <ingrediente>
                Mantequilla
                <cantidad unidad="gramo">100</cantidad>
                </ingrediente>
                <ingrediente> Sal </ingrediente>
                <ingrediente> Pimienta </ingrediente>
                <ingrediente>
                Caldo
                <cantidad unidad="mililitro">1000</cantidad>
                </ingrediente>
                <ingrediente>
                Vino blanco
                <cantidad unidad="chorro">1</cantidad>
                </ingrediente>
            </ingredientes>
            <instrucciones>
                <paso>Picamos la cebolla y la pochamos con la mitad de la mantequilla</paso>
                <paso>Cuando esté transparente, echamos el azafrán, el vino y dejamos que reduzca</paso>
                <paso>A continuación, incorporamos el arroz, lo sofreímos un poco</paso>
                <paso>Vamos añadiendo el cado caliente poco a poco mientras removemos</paso>
                <paso>Salpimientamos</paso>
                <paso>Cuando esté casi hecho, agregamos el resto de la mantequilla y queso</paso>
                <paso>Servimos eseguida</paso>
            </instrucciones>
        </receta>
    </pagina>
