=== CuentaEducaSantiago/2324_Imsgi_SantiagoGV/ud4/03/03.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Hechos_historicos">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="hecho" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Descripcion">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:maxLength value="200"></xs:maxLength>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="fecha">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="dia">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                    <xs:minExclusive value="1"></xs:minExclusive>
                                                    <xs:maxExclusive value="31"></xs:maxExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="mes">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                    <xs:minExclusive value="1"></xs:minExclusive>
                                                    <xs:maxExclusive value="12"></xs:maxExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="anyo">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:positiveInteger">
                                                    <xs:minExclusive value="1950"></xs:minExclusive>
                                                    <xs:maxExclusive value="2100"></xs:maxExclusive>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== CuentaEducaSantiago/2324_Imsgi_SantiagoGV/ud4/03/03.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE Hechos_historicos SYSTEM="03.dtd">-->
<Hechos_historicos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="03.xsd">
    <hecho>
        <Descripcion>Se funda Youtube</Descripcion>
        <fecha dia="15" mes="2" anyo="2005"/>
    </hecho>
    <hecho>
        <Descripcion>Se funda Google</Descripcion>
        <fecha dia="4" mes="9" anyo="1998"/>
    </hecho>
    <hecho>
        <Descripcion>Se funda Facebook</Descripcion>
        <fecha dia="4" mes="2" anyo="2004"/>
    </hecho>
</Hechos_historicos>
