=== CuentaEducaSantiago/2324_Imsgi_SantiagoGV/ud4/01/01.dtd
<!ELEMENT remitente (#PCDATA)>
<!ELEMENT destinatario (#PCDATA)>
<!ELEMENT fecha_mensaje (#PCDATA)>
<!ELEMENT asunto (#PCDATA)>
<!ELEMENT mensaje (#PCDATA)>
<!ELEMENT nombre_fichero (#PCDATA)>
<!ELEMENT tipo_fichero (#PCDATA)>
<!ELEMENT fichero (nombre_fichero, tipo_fichero)>
<!ELEMENT mail (remitente, destinatario+, fecha_mensaje, asunto?, mensaje, fichero)>
<!ATTLIST mail xmlns:xsi CDATA #IMPLIED > <!-- para que este doblemente validado -->
<!ATTLIST mail xsi:noNamespaceSchemaLocation CDATA #IMPLIED >

=== CuentaEducaSantiago/2324_Imsgi_SantiagoGV/ud4/01/01.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE alumno SYSTEM "01.dtd">-->
<mail xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="01.xsd">
    <remitente>random6@gmail.com</remitente>
    <destinatario>Desti9348@gmail.com</destinatario>
    <fecha_mensaje>12/7/2000</fecha_mensaje>
    <asunto></asunto>
    <mensaje>Falta de respuesta</mensaje>
    <fichero>
        <nombre_fichero>Mail</nombre_fichero>
        <tipo_fichero>XML</tipo_fichero>
    </fichero>
</mail>
