=== CuentaEducaSantiago/2324_Imsgi_SantiagoGV/ud4/05/05.dtd
<!ELEMENT City (#PCDATA)>
<!ELEMENT State (#PCDATA)>
<!ELEMENT Zip (#PCDATA)>
<!ELEMENT Address (City, State, Zip)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT ContactoNO (#PCDATA)>
<!ELEMENT LastName (#PCDATA)>
<!ELEMENT FirstName (#PCDATA)>
<!ELEMENT Employee (Address, Email, ContactoNO, LastName, FirstName)>
<!ELEMENT Company (Employee)>
<!ATTLIST Company xmlns:xsi CDATA #IMPLIED > <!-- para que este doblemente validado -->
<!ATTLIST Company xsi:noNamespaceSchemaLocation CDATA #IMPLIED >

=== CuentaEducaSantiago/2324_Imsgi_SantiagoGV/ud4/05/05.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--<!DOCTYPE alumno SYSTEM "05.dtd">-->
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="03.xsd">
    <Employee>
        <FirstName>Juan</FirstName>
        <LastName>Sanchez</LastName>
        <ContactoNO>123456789</ContactoNO>
        <Email>juansanchez@company.com</Email>
        <Address>
            <City>Bangalore</City>
            <State>Karnataka</State>
            <Zip>560212</Zip>
        </Address>
    </Employee>
</Company>
